"use client";
import type { Track } from "@auralis/shared";
import { DownloadSimple, DotsThree, Heart, MagnifyingGlass, MusicNotes, Pause, Play, SlidersHorizontal, Sparkle, Trash } from "@phosphor-icons/react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import Link from "next/link";
import { useMemo, useState } from "react";
import { api } from "@/lib/api";
import { usePlayer, useToasts } from "@/lib/store";
import { formatTime } from "./mini-player";
const filters = ["All", "AI generated", "Remixes", "Uploads", "Favorites"];
export function Library() { const [search, setSearch] = useState(""); const [filter, setFilter] = useState("All"); const [menu, setMenu] = useState<string | null>(null); const client = useQueryClient(); const push = useToasts((s) => s.push); const {current, playing, setTrack, toggle} = usePlayer(); const {data: tracks = [], isLoading, isError} = useQuery({queryKey: ["tracks"], queryFn: () => api.tracks()}); const update = useMutation({mutationFn: ({id, payload}: {id: string; payload: object}) => api.updateTrack(id, payload), onSuccess: () => client.invalidateQueries({queryKey: ["tracks"]})}); const remove = useMutation({mutationFn: api.deleteTrack, onSuccess: () => { push("Track moved out of the library."); client.invalidateQueries({queryKey: ["tracks"]}); }}); const visible = useMemo(() => tracks.filter((track) => { const matchSearch = `${track.title} ${track.prompt} ${track.tags.join(" ")}`.toLowerCase().includes(search.toLowerCase()); const matchFilter = filter === "All" || (filter === "AI generated" && track.provenance === "ai_generated") || (filter === "Remixes" && ["remix", "cover", "repaint"].includes(track.provenance)) || (filter === "Uploads" && track.provenance === "uploaded") || (filter === "Favorites" && track.favorite); return matchSearch && matchFilter; }), [tracks, search, filter]);
  return <div className="page-wrap library-page"><div className="page-title library-title"><div><span className="eyebrow"><MusicNotes /> Your sound archive</span><h1>Library</h1><p>Every sketch, source, and finished signal—kept with its creative history.</p></div><div className="search-box"><MagnifyingGlass /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search tracks, prompts, tags…" /></div></div><div className="filter-bar">{filters.map((item) => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item}</button>)}<span /><button><SlidersHorizontal /> Filters</button></div>{isLoading ? <LibrarySkeleton /> : isError ? <Empty title="The library signal is offline." copy="Start the API and this archive will reconnect automatically." /> : visible.length === 0 ? <Empty title="No tracks in this frequency." copy="Try a different filter, or make your first song." /> : <div className="track-table"><div className="track-row table-head"><span>Title</span><span>Provenance</span><span>BPM</span><span>Key</span><span>Duration</span><span /></div>{visible.map((track) => <div className="track-row" key={track.id}><div className="track-title-cell"><button className="row-play" onClick={() => current?.id === track.id ? toggle() : setTrack(track)} aria-label={`Play ${track.title}`}>{current?.id === track.id && playing ? <Pause weight="fill" /> : <Play weight="fill" />}</button><div className="cover-tile"><Sparkle /></div><div><Link href={`/tracks/${track.id}`}>{track.title}</Link><span>{track.tags.slice(0, 2).join(", ") || track.source_type}</span></div></div><span><Provenance value={track.provenance} /></span><span>{track.bpm ?? "—"}</span><span>{track.musical_key ?? "—"}</span><span>{formatTime(track.duration)}</span><div className="row-actions"><button className={track.favorite ? "liked" : ""} onClick={() => update.mutate({id: track.id, payload: {favorite: !track.favorite}})} aria-label="Favorite"><Heart weight={track.favorite ? "fill" : "regular"} /></button><button onClick={() => setMenu(menu === track.id ? null : track.id)} aria-label="Track actions"><DotsThree /></button>{menu === track.id && <div className="action-menu"><a href={api.download(track.id)}><DownloadSimple /> Download</a><button onClick={() => { const title = window.prompt("Rename track", track.title); if (title) update.mutate({id: track.id, payload: {title}}); }}><Sparkle /> Rename</button><button className="danger" onClick={() => remove.mutate(track.id)}><Trash /> Delete</button></div>}</div></div>)}</div>}</div>;
}
function Provenance({value}: {value: Track["provenance"]}) { return <span className={`provenance ${value}`}>{value.replaceAll("_", " ")}</span>; }
function Empty({title, copy}: {title: string; copy: string}) { return <div className="empty-state"><MusicNotes /><h2>{title}</h2><p>{copy}</p><Link className="primary-button" href="/create">Create a song</Link></div>; }
function LibrarySkeleton() { return <div className="track-table skeleton">{Array.from({length: 5}, (_, index) => <div className="track-row" key={index}><i /><i /><i /><i /><i /></div>)}</div>; }
