"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { CheckCircle, FileAudio, Scissors, Sparkle, UploadSimple, Waveform } from "@phosphor-icons/react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { api } from "@/lib/api";
import { useToasts } from "@/lib/store";
const uploadSchema = z.object({rights: z.literal(true, {error: "Confirm you have the rights to transform this audio."})});
type UploadForm = z.infer<typeof uploadSchema>;
const modes = [{id: "cover", title: "Cover", icon: Sparkle, copy: "Reinterpret the arrangement with new musical direction."}, {id: "remix", title: "Style remix", icon: Waveform, copy: "Carry the source into a new genre, mood, or production era."}, {id: "repaint", title: "Repaint section", icon: Scissors, copy: "Regenerate a selected region while preserving the rest."}, {id: "stems", title: "Separate stems", icon: FileAudio, copy: "Extract vocals, drums, bass, and remaining instruments."}, {id: "vocal-to-bgm", title: "Vocal to BGM", icon: CheckCircle, copy: "Build an accompaniment around an authorized vocal."}];
export function RemixStudio() { const [file, setFile] = useState<File | null>(null); const [mode, setMode] = useState("cover"); const [selectedTrack, setSelectedTrack] = useState(""); const [prompt, setPrompt] = useState("Cinematic electronic arrangement with crisp drums and wide analogue synths"); const push = useToasts((s) => s.push); const client = useQueryClient(); const {register, handleSubmit, formState: {errors}} = useForm<UploadForm>({resolver: zodResolver(uploadSchema)}); const {data: tracks = []} = useQuery({queryKey: ["tracks"], queryFn: () => api.tracks()}); const upload = useMutation({mutationFn: api.upload, onSuccess: (track) => { push("Source audio uploaded and analyzed."); setSelectedTrack(track.id); client.invalidateQueries({queryKey: ["tracks"]}); }, onError: (error) => push(error.message, "error")}); const transform = useMutation({mutationFn: () => api.transform(mode, {track_id: selectedTrack, prompt, rights_confirmed: true}), onSuccess: () => push(`${modes.find((item) => item.id === mode)?.title} entered the generation queue.`), onError: (error) => push(error.message, "error")}); const submitUpload = () => { if (!file) return push("Choose an audio file first.", "error"); const body = new FormData(); body.set("file", file); body.set("rights_confirmed", "true"); upload.mutate(body); };
  return <div className="page-wrap remix-page"><div className="page-title"><div><span className="eyebrow"><Waveform /> Transform with reference audio</span><h1>Remix with intent.</h1><p>Bring your own audio. Auralis keeps the source, consent, and every generated version connected.</p></div></div><div className="remix-grid"><form className="upload-panel" onSubmit={handleSubmit(submitUpload)}><label className="drop-zone"><input type="file" accept="audio/*" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><UploadSimple /><strong>{file?.name ?? "Drop audio here"}</strong><span>WAV, MP3, M4A, FLAC, or OGG · up to 100 MB</span></label><label className="consent-check"><input type="checkbox" {...register("rights")} /><i><CheckCircle weight="fill" /></i><span>I confirm I own this audio or have permission to upload, transform, and generate derivative works from it.</span></label>{errors.rights && <p className="field-error">{errors.rights.message}</p>}<button className="primary-button" disabled={upload.isPending}>{upload.isPending ? "Analyzing…" : "Upload and analyze"}</button></form><section className="mode-panel"><div className="field-group"><label>Source track</label><select value={selectedTrack} onChange={(event) => setSelectedTrack(event.target.value)}><option value="">Choose an uploaded or generated track</option>{tracks.map((track) => <option key={track.id} value={track.id}>{track.title}</option>)}</select></div><div className="mode-grid">{modes.map(({id, title, icon: Icon, copy}) => <button key={id} className={mode === id ? "selected" : ""} onClick={() => setMode(id)}><Icon /><strong>{title}</strong><span>{copy}</span></button>)}</div><div className="field-group"><label>Creative direction</label><textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} /></div><button className="generate-button full" disabled={!selectedTrack || transform.isPending} onClick={() => transform.mutate()}><Sparkle weight="fill" />{transform.isPending ? "Sending…" : "Create transformation"}</button></section></div></div>;
}
