"use client";
import { ArrowLeft, CalendarBlank, DownloadSimple, GitBranch, Heart, MusicNotes, Pause, Play, Sparkle, Waveform } from "@phosphor-icons/react";
import { useQuery } from "@tanstack/react-query";
import Link from "next/link";
import { api } from "@/lib/api";
import { usePlayer } from "@/lib/store";
import { formatTime } from "./mini-player";
import { AudioWaveform } from "./waveform";
export function TrackDetail({id}: {id: string}) { const {data: track, isLoading, isError} = useQuery({queryKey: ["track", id], queryFn: () => api.track(id)}); const {current, playing, setTrack, toggle} = usePlayer(); if (isLoading) return <div className="page-wrap"><div className="detail-skeleton" /></div>; if (isError || !track) return <div className="page-wrap"><div className="empty-state"><MusicNotes /><h2>Track not found</h2><Link className="primary-button" href="/library">Back to library</Link></div></div>; const isCurrent = current?.id === track.id; return <div className="page-wrap detail-page"><Link className="back-link" href="/library"><ArrowLeft /> Library</Link><section className="detail-hero"><div className="detail-art"><Sparkle weight="fill" /></div><div className="detail-copy"><span className="eyebrow">{track.provenance.replaceAll("_", " ")} · version {track.version}</span><h1>{track.title}</h1><p>{track.prompt || "Uploaded source audio"}</p><div className="detail-actions"><button className="play-main" onClick={() => isCurrent ? toggle() : setTrack(track)}>{isCurrent && playing ? <Pause weight="fill" /> : <Play weight="fill" />}{isCurrent && playing ? "Pause" : "Play"}</button><a className="secondary-button" href={api.download(track.id)}><DownloadSimple /> Download</a><button className="icon-button"><Heart /></button></div></div></section><section className="detail-wave"><AudioWaveform url={track.has_audio ? api.audio(track.id) : undefined} /><div className="detail-facts"><span><b>{formatTime(track.duration)}</b>Duration</span><span><b>{track.bpm ?? "—"}</b>BPM</span><span><b>{track.musical_key ?? "—"}</b>Key</span><span><b><CalendarBlank /> {new Date(track.created_at).toLocaleDateString()}</b>Created</span></div></section><div className="detail-columns"><section><h2>Creative brief</h2><p>{track.prompt || "No generation prompt—this is source audio."}</p><div className="tags">{track.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><h2>Lyrics</h2><pre>{track.lyrics || "Instrumental / no lyrics stored"}</pre></section><aside><h2><GitBranch /> Version history</h2><div className="version-list"><div className="version active"><b>v{track.version}</b><span>{track.title}</span><small>Current</small></div>{track.versions.map((version) => <Link href={`/tracks/${version.id}`} className="version" key={version.id}><b>v{version.version}</b><span>{version.title}</span><small>{version.provenance}</small></Link>)}</div><Link className="primary-button" href={`/remix?track=${track.id}`}><Waveform /> Create a new version</Link></aside></div></div>; }
